name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  save-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Save calico cni
        run: docker pull docker.io/calico/cni:v3.24.5; docker save docker.io/calico/cni:v3.24.5 -o calico-cni.tar.gz
      - name: Save calico node
        run: docker pull docker.io/calico/node:v3.24.5; docker save docker.io/calico/node:v3.24.5 -o calico-node.tar.gz
      - name: Save calico kube controllers
        run: docker pull docker.io/calico/kube-controllers:v3.24.5; docker save docker.io/calico/kube-controllers:v3.24.5 -o calico-kube-controllers.tar.gz
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v3.24.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: v3.24.5

      # Creates the new release with the binary as a release asset.
      # If the previous Action was skipped, then this keeps the same tag as the
      # previous release.
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "v3.24.5"
          name: "v3.24.5"
          tag_name: v3.24.5
          files: |
            calico-cni.tar.gz
            calico-node.tar.gz
            calico-kube-controllers.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
